### ISSUE TITLE
Location Updates Not Working

### ISSUE THREAD

**Issue by majidalik** [phunware/maas-location-android-sdk#25] opened 2020-07-20 10:23 UTC
There is nothing happening in callbacks after invoke requestLocationUpdates().
We want to track user information from integrated beacons in background/foreground without map.
So We have implement this sdk but there is no any callback occurring either error or success location.

Here is code:

import androidx.annotation.NonNull;
import androidx.appcompat.app.AlertDialog;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.app.ActivityCompat;
import androidx.core.content.ContextCompat;

import android.Manifest;
import android.app.Activity;
import android.content.Context;
import android.content.DialogInterface;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.location.Location;
import android.net.Uri;
import android.os.Build;
import android.os.Bundle;
import android.provider.Settings;
import android.util.Log;
import android.widget.Toast;

import com.phunware.location.provider_managed.ManagedProviderFactory;
import com.phunware.location.provider_managed.PwManagedLocationProvider;
import com.phunware.location_core.PwLocationListener;
import com.phunware.location_core.PwLocationUpdateResult;

import java.lang.ref.WeakReference;

public class Main2Activity extends AppCompatActivity {
    Context context;
    PwManagedLocationProvider provider;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main2);
        context = this;

        ManagedProviderFactory.ManagedProviderFactoryBuilder builder =
                new ManagedProviderFactory.ManagedProviderFactoryBuilder();

        WeakReference<Context> context = new WeakReference<Context>(this);
        provider = (PwManagedLocationProvider) builder.application(getApplication())
                .context(context)
                .buildingId("10..01")
                .build()
                .createLocationProvider();
        if (ifPermissionsAllowed()) {
            provider.requestLocationUpdates(listener);
        }

    }

    public Boolean ifPermissionsAllowed() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            if (ActivityCompat.checkSelfPermission(context, Manifest.permission.ACCESS_FINE_LOCATION) == PackageManager.PERMISSION_GRANTED ||
                    ActivityCompat.checkSelfPermission(context, Manifest.permission.ACCESS_COARSE_LOCATION) == PackageManager.PERMISSION_GRANTED ||
                    ActivityCompat.checkSelfPermission(context, Manifest.permission.ACCESS_BACKGROUND_LOCATION) == PackageManager.PERMISSION_GRANTED) {
                return true;

            } else {

                requestPermissions(new String[]{Manifest.permission.ACCESS_COARSE_LOCATION, Manifest.permission.ACCESS_FINE_LOCATION},
                        10);
                return false;
            }
        } else {
            return true;
        }
    }

    PwLocationListener listener = new PwLocationListener() {
        @Override
        public void onLocationUpdateFailed(PwLocationUpdateResult pwLocationUpdateResult) {
            Log.e("", "");
        }

        @Override
        public void onLocationChanged(Location location) {
            Log.e("", "" + location);
        }

        @Override
        public void onStatusChanged(String s, int i, Bundle bundle) {
            Log.e("", "" + s);
            Log.e("", "" + i);
        }

        @Override
        public void onProviderEnabled(String s) {
            Log.e("", "" + s);
        }

        @Override
        public void onProviderDisabled(String s) {
            Log.e("", "" + s);
        }
    };

    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        if (requestCode == 10) {
            if (grantResults.length > 0 && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
                provider.requestLocationUpdates(listener);
            } else {
                if (!ActivityCompat.shouldShowRequestPermissionRationale((Activity) context, Manifest.permission.ACCESS_FINE_LOCATION)) {
                    // If User Checked 'Don't Show Again' checkbox for runtime permission, then navigate user to Settings
                    AlertDialog.Builder dialog = new AlertDialog.Builder(context);
                    dialog.setTitle("Permission Required");
                    dialog.setCancelable(false);
                    dialog.setMessage("You have to Allow permission to access user location");
                    dialog.setPositiveButton("Settings", new DialogInterface.OnClickListener() {
                        @Override
                        public void onClick(DialogInterface dialog, int which) {
                            Intent i = new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS, Uri.fromParts("package",
                                    context.getPackageName(), null));
                            //i.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                            startActivityForResult(i, 1001);
                        }
                    });
                    AlertDialog alertDialog = dialog.create();
                    alertDialog.show();
                }
                //code for deny
            }
        }
    }

}
@svavilikolanu-phunware @avakkachen

**Comment by tstump-phunware** [comment] 2023-03-03 10:56
Closing, as the team has changed and our SDKs have greatly improved since this issue was filed. Please try 4.4.0.

For future issues, please include a bare minimum sample project that reproduces the issue.

**Closed by tstump-phunware** 2023-03-03 10:56 UTC
